# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        env:
          LIMA_START_ARGS: --cpus 4 --memory 8
      - uses: pre-commit/action@v3.0.1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "bin"
      - name: execute install.sh
        run: bash -n bin/install.sh
      - name: execute config
        run: bash -n bin/setup_config
